# Generated by Django 2.2.7 on 2020-01-21 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_answer_postquiz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
