# Generated by Django 2.2.7 on 2020-01-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_delete_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postquiz',
            name='title',
        ),
        migrations.AddField(
            model_name='postquiz',
            name='answer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Правильный ответ'),
        ),
        migrations.AddField(
            model_name='postquiz',
            name='option1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Вариант ответа №1'),
        ),
        migrations.AddField(
            model_name='postquiz',
            name='option2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Вариант ответа №2'),
        ),
        migrations.AddField(
            model_name='postquiz',
            name='option3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Вариант ответа №3'),
        ),
        migrations.AddField(
            model_name='postquiz',
            name='option4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Вариант ответа №4'),
        ),
        migrations.AddField(
            model_name='postquiz',
            name='question',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Вопрос'),
        ),
    ]
