# Generated by Django 3.0.2 on 2020-01-22 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20200121_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postquiz',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='postquiz',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='postquiz',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='postquiz',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='postquiz',
            name='option4',
        ),
        migrations.RemoveField(
            model_name='postquiz',
            name='question',
        ),
        migrations.AddField(
            model_name='postquiz',
            name='num_of_quest',
            field=models.FloatField(blank=True, max_length=2, null=True, verbose_name='Количество вопросов'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=200, null=True, verbose_name='Вопрос')),
                ('option1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Вариант ответа №1')),
                ('option2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Вариант ответа №2')),
                ('option3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Вариант ответа №3')),
                ('option4', models.CharField(blank=True, max_length=100, null=True, verbose_name='Вариант ответа №4')),
                ('answer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Правильный ответ')),
                ('post_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.PostQuiz')),
            ],
        ),
    ]
