# Generated by Django 3.0.2 on 2020-01-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20200122_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='postquiz',
            name='name_quiz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название викторины'),
        ),
    ]
